image: rust:latest

before_script:
  - apt-get update -qq && apt-get install -y -qq libdbus-1-dev libclang-dev libudev-dev

stages:
    - test
    - build

test:
  script:
    - rustup component add clippy
    - cargo check
    - cargo clippy
    - cargo test

build:
  only:
    - main
  script:
    - cargo install cargo-vendor-filterer
    - make && make vendor
  artifacts:
    paths:
    - vendor-*.tar.xz
    - cargo-config

variables:
  GIT_SUBMODULE_STRATEGY: normal

